# Generated by Django 5.0 on 2023-12-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Назва статистики')),
                ('country', models.CharField(max_length=30, verbose_name='Країна')),
                ('year', models.CharField(max_length=30, verbose_name='Рік')),
                ('budget', models.CharField(max_length=30, verbose_name='Бюджет')),
            ],
        ),
    ]
