# Generated by Django 5.0 on 2023-12-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabla',
            new_name='Table',
        ),
    ]
