# Generated by Django 5.0 on 2023-12-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_tabla_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='budget',
            new_name='nums',
        ),
    ]
